Seq validator
-------------

Sequences in YAML are denoted by a series of dashes ('-')
and parsed as a list in python.

Validating sequences of a particular type can be done with
the Seq validator, specifying the type.

See also UniqueSeq and FixedSeq for other types of sequence
validation.

.. code-block:: python

    from strictyaml import Seq, Str, Int, load

With variable 'valid_sequence':

.. code-block:: yaml

  - 1
  - 2
  - 3



.. code-block:: python

    load(valid_sequence, Seq(Str())) == ["1", "2", "3", ]
    >>> True



.. code-block:: python

    load(valid_sequence, Seq(Str())).is_sequence()
    >>> True



.. code-block:: python

    load(valid_sequence, Seq(Str())).text
    >>> EXCEPTION RAISED:
      is a sequence, has no text value.

With variable 'invalid_sequence_1':

.. code-block:: yaml

  a: 1
  b: 2
  c: 3



.. code-block:: python

    load(invalid_sequence_1, Seq(Str()))
    >>> EXCEPTION RAISED:
      when expecting a sequence
        in "<unicode string>", line 1, column 1:
          a: '1'
           ^ (line: 1)
      found non-sequence
        in "<unicode string>", line 3, column 1:
          c: '3'
          ^ (line: 3)

With variable 'invalid_sequence_2':

.. code-block:: yaml

  - 2
  - 3
  - a:
    - 1
    - 2



.. code-block:: python

    load(invalid_sequence_2, Seq(Str()))
    >>> EXCEPTION RAISED:
      when expecting a str
        in "<unicode string>", line 3, column 1:
          - a:
          ^ (line: 3)
      found mapping/sequence
        in "<unicode string>", line 5, column 1:
            - '2'
          ^ (line: 5)

With variable 'invalid_sequence_3':

.. code-block:: yaml

  - 1.1
  - 1.2



.. code-block:: python

    load(invalid_sequence_3, Seq(Int()))
    >>> EXCEPTION RAISED:
      when expecting an integer
      found non-integer
        in "<unicode string>", line 1, column 1:
          - '1.1'
           ^ (line: 1)

With variable 'invalid_sequence_4':

.. code-block:: yaml

  - 1
  - 2
  - 3.4



.. code-block:: python

    load(invalid_sequence_4, Seq(Int()))
    >>> EXCEPTION RAISED:
      when expecting an integer
      found non-integer
        in "<unicode string>", line 3, column 1:
          - '3.4'
          ^ (line: 3)


Page automatically generated by hitchdoc from:
  hitch/sequence.story